### PR TITLE
Replace AsRef<[u8]> with Bytes, stop using mmap

### LINKED ISSUE #39: How to represent a sequence of bytes
I'm opening up this issue to discuss the appropriate representation for a buffer (i.e. an arbitrary contiguous sequence of bytes) in `terminus-store`. This discussion will help me to get an understanding for the motivation and mechanics of the current approach and to probe for reactions to an alternative approach, which I propose at the end. Please feel free to comment on anything or to correct my understanding if necessary.

Currently, the predominant view of a buffer appears to be `M: AsRef<[u8]>`. This type implies two things:

1. A given `data: M` has the operation `data.as_ref()` that returns `&[u8]`. This gives a read-only view of a buffer that can be shared between threads without the option of writing to it.
2. The struct containing the `data: M` owns the value referencing the buffer. There is no borrowing of references here.

This appears to have been changed from a previously predominant view of a buffer as a slice: `data: &'a [u8]` (1deedbf3e73d99012e70d96fe821cbc7b26d454e, bf6416bc6cf4c83b9a179e0a6a41dd21b000c69b, ad7dd425e85f75d9bdb7336a54a5e3560acbfed2, e5a50a00338ee5304327e424b72ca7eaf584eccc, c6a14f90b505efba9571da19e6f7f3faa84be5f7). This view meant:

1. The `data: &'a [u8]` cannot be shared between threads.
2. The view into the data lasts no longer than the buffer's owner, who has the `'a` lifetime.

Now, given that the buffers currently seem to be backed by one of the two following `struct`s:

* `pub struct SharedVec(pub Arc<Vec<u8>>);`
* `pub struct SharedMmap(Option<Arc<FileBacking>>);`

which both have `Arc`, I presume that the data is being shared read-only between threads. (I'm actually not yet clear on where the sharing is occurring, so if you want to enlighten me, I'd appreciate it!) If there was no sharing, I think the slice approach is better, since (a) there is less runtime work to manage usage of the buffers and (b) the type system keeps track of the lifetimes.

I think using `M: AsRef<[u8]>` is somewhat painful as schema for typing a buffer. It's too general and leads to trait bounds such as `M: 'static + AsRef<[u8]> + Clone + Send + Sync` in many places.

After doing some research, I think something like [`Bytes`](https://docs.rs/bytes/0.5.4/bytes/struct.Bytes.html) from the [`bytes`](https://github.com/tokio-rs/bytes) crate would work better. `Bytes` is a thread-shareable container representing a contiguous sequence of bytes. It satisfies `'static + AsRef<[u8]> + Clone + Send + Sync`. It also supports operations like `split_to` and `split_off`, which I think would work well when you want to segment a buffer into different representations. Replacing `data: M` with `data: Bytes` would make many of the trait bounds disappear.

Unfortunately, `Bytes` does not support `memmap::Mmap`, which means it would not suit `terminus-store`'s current usage of `AsRef<[u8]>`. However, I've already implemented an adaptation of `Bytes` that does support `memmap::Mmap`. Others have, too. See https://github.com/tokio-rs/bytes/issues/359.

Here are some questions prompted by the above:

* What's the best way to represent a contiguous sequence of bytes in `terminus-store`?
* Does it need to be read-only?
* Does it need to be shared between threads?
* Would it be useful to use a less general type than `AsRef<[u8]>`? Could that type be a `struct` instead of a set of trait bounds?

### PR DESCRIPTION
**Pull request by spl**
* Transition all uses of `AsRef<[u8]>` to `Bytes`
* Use `clone` in `LogArrayIterator`, remove `OwnedLogArrayIterator`
* Track `first` element in `LogArray`, remove `LogArraySlice`
* Use `Bytes` in `FileLoad`, remove `Map` associated type
* Read files into memory, remove `memmap::Mmap`

Closes #39

### CODE REVIEW

**Comment by spl** [comment]
Also, something I didn't mention in #39 or here, `Bytes` can be thought of as `Arc<Vec<u8>>` (which this PR is replacing in some uses), but the former is more space-efficient than the latter, and it _should_ ¹ be more performant as well.

¹ <sub>Performance should always come with a footnote that mentions (a) how one never knows until one runs the benchmarks, (b) even if one runs the benchmarks, one still only has a bit more confidence without studying an actual workload, and (c) even if one studies real-world workloads, there's still no guarantee for all the other real-world workloads. I didn't run the benchmarks.</sub>

**Comment by spl** [comment]
I'm sure you're busy right now. I just wanted to know what your plan with this PR might be. I hope to eventually submit some more PRs, but I don't want to create conflicts with this one, which touches a number of files and lines. Is this something you'd rather put off until later? Thanks!

**Comment by matko** [comment]
I like what you've done to the place :).

Merging now. Sorry it took so long.

**Comment by spl** [comment]
> I like what you've done to the place :).

😆

> Merging now. Sorry it took so long.

No problem!

**Pull request merged**
